# Generated by Django 2.2.4 on 2019-08-13 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_field', models.CharField(max_length=500)),
                ('occupations', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('skills', models.CharField(max_length=500)),
                ('education', models.CharField(max_length=500)),
                ('employers', models.CharField(max_length=500)),
                ('job_data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('profession', models.CharField(max_length=500)),
                ('advice_topics', models.CharField(max_length=500)),
                ('image_url', models.CharField(max_length=500)),
                ('company', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentors', to='ment_app.Career')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('body', models.TextField()),
                ('date', models.CharField(max_length=500)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='ment_app.Mentor')),
            ],
        ),
    ]
