# Generated by Django 2.2.4 on 2019-08-16 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ment_app', '0002_auto_20190816_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='onetcode',
        ),
        migrations.RemoveField(
            model_name='career',
            name='state',
        ),
    ]
