# Generated by Django 2.2.4 on 2019-08-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ment_app', '0003_auto_20190816_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='onetcode',
            field=models.CharField(default='29-1171.00', max_length=100),
        ),
        migrations.AddField(
            model_name='career',
            name='state',
            field=models.CharField(default='GA', max_length=100),
        ),
    ]
