# Generated by Django 2.2.4 on 2019-08-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ment_app', '0004_auto_20190816_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='onetcode',
            field=models.CharField(default='REQUIRED', max_length=100),
        ),
        migrations.AlterField(
            model_name='career',
            name='state',
            field=models.CharField(default='REQUIRED', max_length=100),
        ),
    ]
