# Generated by Django 2.2.4 on 2019-08-16 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ment_app', '0005_auto_20190816_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='education',
        ),
        migrations.RemoveField(
            model_name='career',
            name='employers',
        ),
        migrations.RemoveField(
            model_name='career',
            name='job_data',
        ),
        migrations.RemoveField(
            model_name='career',
            name='skills',
        ),
    ]
