# Generated by Django 2.2.4 on 2019-08-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ment_app', '0007_career_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='image',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
